name: build-project

on:
  push:
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ccache: ccache  

jobs:
  build-project:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cfg:
          - { target: linux64, libs: 64gcc6 }
    env:
      TARGET: ${{ matrix.cfg.target }}
      MY_PROJECT_DIR: "fireflies_port"

    steps:
    - name: Checkout openFrameworks Repository
      uses: actions/checkout@v4
      with:
        repository: openframeworks/openFrameworks
        path: of_root

    - name: Checkout Your Project Repository
      uses: actions/checkout@v4
      with:
        path: of_root/apps/myApps/$MY_PROJECT_DIR

    - name: Checkout ofxImGui addon
      uses: actions/checkout@v4
      with:
        repository:  jvcleave/ofxImGui
        path: of_root/addons/ofxImGui
        ref: develop
    - name: Checkout ofxTextureRecorder addon
      uses: actions/checkout@v4
      with:
        repository:  arturoc/ofxTextureRecorder
        path: of_root/addons/ofxTextureRecorder

    - name: Download openFrameworks Libraries
      run: cd of_root && ./scripts/linux/download_libs.sh -a ${{ matrix.cfg.libs }}

    - name: Install Dependencies
      run: cd of_root && ./scripts/ci/${{ matrix.cfg.target }}/install.sh

    - name: Build openFrameworks Core
      run: cd of_root && ./scripts/ci/${{ matrix.cfg.target }}/build.sh

    - name: Build Your Project
      run: |
        cd of_root/apps/myApps/$MY_PROJECT_DIR
        make

    - name: Upload Artifact (Binary)
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.cfg.target }}-binary
        path: of_root/apps/myApps/$MY_PROJECT_DIR/bin
